# Generated by Django 5.2.10 on 2026-01-31 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='İngilizce Adı')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='İkon')),
                ('mode', models.CharField(choices=[('social', 'Sosyal'), ('professional', 'Profesyonel'), ('both', 'Her İkisi')], default='both', max_length=20, verbose_name='Mod')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Aktivite Kategorisi',
                'verbose_name_plural': 'Aktivite Kategorileri',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('mode', models.CharField(choices=[('social', 'Sosyal'), ('professional', 'Profesyonel')], default='social', max_length=20, verbose_name='Mod')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Enlem')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='Boylam')),
                ('address_display', models.CharField(max_length=200, verbose_name='Görünen Adres')),
                ('address_full', models.CharField(blank=True, max_length=500, verbose_name='Tam Adres')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Şehir')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='İlçe')),
                ('start_time', models.DateTimeField(verbose_name='Başlangıç')),
                ('end_time', models.DateTimeField(verbose_name='Bitiş')),
                ('max_participants', models.PositiveIntegerField(default=10, verbose_name='Maksimum Katılımcı')),
                ('current_participants', models.PositiveIntegerField(default=0, verbose_name='Mevcut Katılımcı')),
                ('is_instant', models.BooleanField(default=False, verbose_name='Anlık Plan')),
                ('is_group_join', models.BooleanField(default=False, verbose_name='Grup Olarak Katılım')),
                ('group_size_min', models.PositiveIntegerField(default=1, verbose_name='Min Grup Boyutu')),
                ('group_size_max', models.PositiveIntegerField(default=5, verbose_name='Max Grup Boyutu')),
                ('company_domain_filter', models.CharField(blank=True, max_length=100, null=True, verbose_name='Şirket Domain Filtresi')),
                ('is_public_seo', models.BooleanField(default=False, verbose_name='Halka Açık (SEO)')),
                ('seo_slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='SEO URL')),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('full', 'Dolu'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='active', max_length=20, verbose_name='Durum')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_activities', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='activities.activitycategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Aktivite',
                'verbose_name_plural': 'Aktiviteler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='activities/', verbose_name='Görsel')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Ana Görsel')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='activities.activity', verbose_name='Aktivite')),
            ],
            options={
                'verbose_name': 'Aktivite Görseli',
                'verbose_name_plural': 'Aktivite Görselleri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ActivityParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='Başvuru Mesajı')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi'), ('cancelled', 'İptal Edildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('is_group', models.BooleanField(default=False, verbose_name='Grup Olarak')),
                ('group_member_count', models.PositiveIntegerField(default=1, verbose_name='Grup Üye Sayısı')),
                ('group_members_info', models.JSONField(blank=True, default=list, verbose_name='Grup Üyeleri')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Başvuru Tarihi')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Yanıt Tarihi')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='activities.activity', verbose_name='Aktivite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL, verbose_name='Katılımcı')),
            ],
            options={
                'verbose_name': 'Katılım',
                'verbose_name_plural': 'Katılımlar',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['mode', 'status', 'is_active'], name='activities__mode_8279ac_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['city', 'district'], name='activities__city_8eed91_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['start_time'], name='activities__start_t_e1d6ff_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['is_public_seo', 'seo_slug'], name='activities__is_publ_1408f4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='activityparticipation',
            unique_together={('activity', 'user')},
        ),
    ]
