# Generated by Django 5.2.10 on 2026-01-31 18:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Slug')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('document_type', models.CharField(choices=[('privacy_policy', 'Gizlilik Politikası'), ('terms_of_service', 'Kullanım Şartları'), ('kvkk', 'KVKK Aydınlatma Metni'), ('cookie_policy', 'Çerez Politikası')], max_length=50, verbose_name='Belge Tipi')),
                ('content', models.TextField(verbose_name='İçerik (HTML)')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Versiyon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yasal Belge',
                'verbose_name_plural': 'Yasal Belgeler',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Telefon')),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='Görünen Ad')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profil Fotoğrafı')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Hakkımda')),
                ('current_mode', models.CharField(choices=[('social', 'Sosyal'), ('professional', 'Profesyonel')], default='social', max_length=20, verbose_name='Aktif Mod')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='GitHub Profili')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn Profili')),
                ('portfolio_url', models.URLField(blank=True, null=True, verbose_name='Portfolyo')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='Yetenekler')),
                ('is_verified_company', models.BooleanField(default=False, verbose_name='Şirket Doğrulandı')),
                ('company_domain', models.CharField(blank=True, max_length=100, null=True, verbose_name='Şirket Domaini')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Şirket/Üniversite Adı')),
                ('fcm_token', models.TextField(blank=True, null=True, verbose_name='FCM Token')),
                ('is_2fa_enabled', models.BooleanField(default=False, verbose_name='2FA Aktif')),
                ('two_factor_secret', models.CharField(blank=True, max_length=100, null=True)),
                ('privacy_settings', models.JSONField(blank=True, default=dict, verbose_name='Gizlilik Ayarları')),
                ('data_consent_at', models.DateTimeField(blank=True, null=True, verbose_name='Veri Onay Tarihi')),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Şartlar Onay Tarihi')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Kayıt Tarihi')),
                ('last_active', models.DateTimeField(auto_now=True, verbose_name='Son Aktiflik')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('otp_type', models.CharField(choices=[('email', 'E-posta'), ('phone', 'Telefon'), ('2fa', 'İki Faktörlü Doğrulama')], default='email', max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doğrulama Kodu',
                'verbose_name_plural': 'Doğrulama Kodları',
            },
        ),
        migrations.CreateModel(
            name='BlockedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Engellenme Tarihi')),
                ('reason', models.TextField(blank=True, verbose_name='Sebep')),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL, verbose_name='Engellenen')),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocking', to=settings.AUTH_USER_MODEL, verbose_name='Engelleyen')),
            ],
            options={
                'verbose_name': 'Engellenen Kullanıcı',
                'verbose_name_plural': 'Engellenen Kullanıcılar',
                'unique_together': {('blocker', 'blocked')},
            },
        ),
    ]
