# Generated by Django 5.2.10 on 2026-02-01 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('body', models.TextField(verbose_name='İçerik')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim Tarihi')),
                ('devices_reached', models.IntegerField(default=0, verbose_name='Ulaşılan Cihaz')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Gönderen')),
            ],
            options={
                'verbose_name': 'Toplu Bildirim',
                'verbose_name_plural': 'Toplu Bildirimler',
                'ordering': ['-sent_at'],
            },
        ),
    ]
