# Generated by Django 5.2.10 on 2026-02-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_broadcastnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram Profili'),
        ),
        migrations.AddField(
            model_name='user',
            name='socialrate_url',
            field=models.URLField(blank=True, null=True, verbose_name='SocialRate Profili'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='X (Twitter) Profili'),
        ),
    ]
