# Generated by Django 5.2.10 on 2026-01-31 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='Kelime')),
                ('is_regex', models.BooleanField(default=False, verbose_name='Regex')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Yasaklı Kelime',
                'verbose_name_plural': 'Yasaklı Kelimeler',
            },
        ),
        migrations.CreateModel(
            name='ReportedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('activity', 'Aktivite'), ('user', 'Kullanıcı'), ('message', 'Mesaj')], max_length=20, verbose_name='Şikayet Tipi')),
                ('reason', models.CharField(choices=[('spam', 'Spam'), ('inappropriate', 'Uygunsuz İçerik'), ('harassment', 'Taciz'), ('hate_speech', 'Nefret Söylemi'), ('violence', 'Şiddet'), ('scam', 'Dolandırıcılık'), ('fake_profile', 'Sahte Profil'), ('other', 'Diğer')], max_length=50, verbose_name='Sebep')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('reviewed', 'İncelendi'), ('action_taken', 'İşlem Yapıldı'), ('dismissed', 'Reddedildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Yönetici Notları')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='İnceleme Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme')),
                ('reported_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='activities.activity', verbose_name='Şikayet Edilen Aktivite')),
                ('reported_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='messaging.message', verbose_name='Şikayet Edilen Mesaj')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_against', to=settings.AUTH_USER_MODEL, verbose_name='Şikayet Edilen Kullanıcı')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_reports', to=settings.AUTH_USER_MODEL, verbose_name='Şikayet Eden')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='İnceleyen')),
            ],
            options={
                'verbose_name': 'Şikayet',
                'verbose_name_plural': 'Şikayetler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('warn', 'Uyarı'), ('content_removed', 'İçerik Silindi'), ('user_suspended', 'Kullanıcı Askıya Alındı'), ('user_banned', 'Kullanıcı Yasaklandı'), ('report_dismissed', 'Şikayet Reddedildi')], max_length=50, verbose_name='İşlem')),
                ('reason', models.TextField(verbose_name='Gerekçe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL, verbose_name='Moderatör')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_received', to=settings.AUTH_USER_MODEL, verbose_name='Hedef Kullanıcı')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moderation.reportedcontent', verbose_name='İlgili Şikayet')),
            ],
            options={
                'verbose_name': 'Moderasyon Logu',
                'verbose_name_plural': 'Moderasyon Logları',
                'ordering': ['-created_at'],
            },
        ),
    ]
